import type { VipCard } from '../../types/type'

const cards: VipCard[] = [
	{
		name: 'bonus1',
		title: 'Point bonus',
		text: 'A utiliser sur une évaluation',
		image: 'ecrabouilleur.jpg',
		rarity: 'uncommon',
	},
	{
		name: 'bougeotte',
		title: 'Bougeotte',
		text: 'Je choisis ma place pour une heure (mais mon professeur peut me remettre à mon ancienne pace si je ne suis pas sérieux)',
		image: 'bougeotte.png',
		rarity: 'common',
	},
	{
		name: 'super-bougeotte',
		title: 'Super bougeotte',
		text: 'Je choisis ma place pour une semaine (mais mon professeur peut me remettre à mon ancienne pace si je ne suis pas sérieux)',
		image: 'bougeotte.png',
		rarity: 'common',
	},
	{
		name: 'ecrabouilleur',
		title: 'Ecrabouilleur',
		text: 'Je peux enlever un avertissement.',
		image: 'ecrabouilleur.jpg',
		rarity: 'common',
	},

	{
		name: 'tranquilou',
		title: 'Tranquilou',
		text: "J'ai le droit d'avoir oublié de faire mon travail pour cette fois.",
		image: 'tranquilou.jpg',
		rarity: 'common',
	},
	{
		name: 'batman',
		title: 'Batman and Robin',
		text: "Je peux être l'assistant du professeur pour l'aider à distribuer les feuilles ou pour organiser une activité, un tour de mathémagie.",
		image: 'batman.jpg',
		rarity: 'common',
	},
	{
		name: 'lalala',
		title: 'La la la la la',
		text: "Je peux choisis un morceau de musique pour l'entrée ou la sortie du cours.",
		image: 'musique.png',
		rarity: 'common',
	},
	{
		name: 'captain',
		title: 'Captain',
		text: "Je peux choisir mon rôle lors d'un travail de groupe.",
		image: 'captain.jpg',
		rarity: 'common',
	},
	{
		name: 'choix',
		title: 'Libre choix',
		text: 'Je peux choisir la carte VIP que je veux.',
		image: 'choix.png',
		rarity: 'legendary',
	},
	{
		name: 'soldes',
		title: 'Soldes',
		text: 'Je peux choisir deux autres cartes VIP.',
		image: 'soldes.jpg',
		rarity: 'rare',
	},
	{
		name: 'fame',
		title: 'Walk of fame',
		text: "J'ai le droit à mon moment de gloire : je peux afficher une œuvre personnelle dans la classe, raconter une blague à la classe, .....bref, tout ce qui peut me mettre en  valeur aux yeux de la classe..",
		image: 'hollywood.jpg',
		rarity: 'common',
	},
	{
		name: 'candy',
		title: 'Candy',
		text: "Si mes parents sont d'accord, j'ai le droit à ce que le professeur m'offre un paquet de bonbons.",
		image: 'bonbons.jpg',
		rarity: 'legendary',
	},
	{
		name: 'memoire',
		title: 'Trou de mémoire',
		text: "J'ai le droit d'utiliser mes cahiers pendant une évaluation.",
		image: 'oubli.jpg',
		rarity: 'uncommon',
	},
	{
		name: 'team',
		title: 'My team',
		text: 'Je peux choisir le groupe avec lequel il faudra produire un travail.',
		image: 'travail-groupe.jpg',
		rarity: 'uncommon',
	},
	{
		name: 'help',
		title: 'Help !',
		text: "J'ai le droit à une aide particulière du professeur pendant mon évaluation.",
		image: 'aide.png',
		rarity: 'uncommon',
	},
	{
		name: 'inventeur',
		title: 'Inventeur',
		text: "Je peux proposer l'idée d'une nouvelle carte VIP ( qui devra être validée par le professeur).",
		image: 'inventeur.jpg',
		rarity: 'uncommon',
	},
	{
		name: 'jeu',
		title: 'Jeu maths',
		text: "Je peux choisir le jeu mathématique que l'on va faire.",
		image: 'bingo.jpg',
		rarity: 'uncommon',
	},
	{
		name: 'coup-double',
		title: 'Coup double',
		text: 'Je choisis pour ce trimestre une note qui va compter deux fois.',
		image: '',
		rarity: 'uncommon',
	},
	{
		name: 'throne',
		title: 'Game of throne',
		text: "J'ai le droit d'avoir la chaise du prof pour une heure.",
		image: 'throne.jpg',
		rarity: 'uncommon',
	},
	{
		name: 'mega-soldes',
		title: 'Méga soldes',
		text: 'Je peux piocher 4 nouvelles cartes VIP.',
		image: 'soldes.jpg',
		rarity: 'legendary',
	},
	{
		name: 'super-bonus',
		title: 'Super bonus',
		text: 'Je peux ajouter deux points sur mes évaluations.',
		image: '',
		rarity: 'rare',
	},
	{
		name: 'super-soldes',
		title: 'Super soldes',
		text: 'Je peux piocher 3 nouvelles cartes VIP.',
		image: '',
		rarity: 'rare',
	},
	{
		name: 'mega-bonus',
		title: 'Mega bonus',
		text: 'Je peux ajouter trois points sur mes évaluations.',
		image: '',
		rarity: 'legendary',
	},
	{
		name: 'mathemagie',
		title: 'Mathémagie',
		text: "Je peux assister le professeur pour un tour de mathémagie, ou le professeur peut m'apprendre un tour de mathémagie pour épater mes amis.",
		image: 'mathemagie.jpg',
		rarity: 'legendary',
	},
	{
		name: 'Sheikh',
		title: 'Sheikh / Sheikha',
		text: "Je peux prendre la chaise du professeur, j'ai le droit à un karak, et le professeur m'appelle Sheikh ou Sheikha pendant toutes l'heure.",
		image: 'roi.jpg',
		rarity: 'rare',
	},
]

export default cards
