export const warningCasesShort = [
	'Retard',
	'Matériel',
	'Devoirs',
	'Déplacement',
	'Prise de parole',
	'Dort',
	'Refus de travail',
	'Bavarde',
	'Triche',
	'Absent',
]

export const warningCases: Record<string, Record<string, string>> = {
	fr: {
		Retard: 'Arrive en retard en cours',
		Matériel: "N'a pas son matériel pour travailler",
		Devoirs: 'Devoirs à la maison non faits',
		Déplacement: 'Se déplace en classe sans en avoir eu la permission',
		'Prise de parole': "Prends la parole sans en avoir eu l'autorisation",
		Dort: 'Dort sur sa table',
		'Refus de travail': 'Ne fait pas le travail demandé',
		Bavarde: "Bavarde ou s'amuse au lieu d'écouter et de travailler",
		Triche: "Triche pendant l'évaluation",
		Absent: 'Absent',
	},
	ar: {
		Retard: 'تأخر عن حصة الرياضيات',
		Matériel: 'نقص المواد للدراسة',
		Devoirs: 'الواجبات المنزلية غير منجزة',
		Déplacement: 'التجول في الصف بدون إذن',
		'Prise de parole': 'Prise de parole non autorisée',
		Dort: 'نوم على الطاولة',
		'Refus de travail': 'رفض العمل والقيام بالتمارين المطلوبة',
		Bavarde: 'الدردشة واللعب بدلاً من الاستماع إلى الدرس',
		Triche: 'الغش أثناء الامتحان',
		Absent: 'غياب',
	},
	en: {
		Retard: 'Arrive en retard en cours',
		Matériel: "N'a pas son matériel pour travailler",
		Devoirs: 'Homework not done',
		Déplacement: 'Déplacement non autorisé',
		'Prise de parole': 'Prise de parole non autorisée',
		Dort: 'Dort en classe',
		'Refus de travail': 'Ne fait pas le travail demandé',
		Bavarde: "Bavarde au lieu d'écouter ou de travailler",
		Triche: "Triche pendant l'évaluation",
		Absent: 'Absent',
	},
}
