export const warningCasesShort = [
	'Retard',
	'Matériel',
	'Devoirs',
	'Déplacement',
	'Prise de parole',
	'Dort',
	'Refus de travail',
	'Bavarde',
	'Triche',
	'Absent',
	'Projectile',
]

export const warningCases: Record<string, Record<string, string>> = {
	fr: {
		Retard: 'Arrive en retard en cours',
		Matériel: "N'a pas son matériel pour travailler",
		Devoirs: 'Devoirs à la maison non faits',
		Déplacement: 'Se déplace en classe sans en avoir eu la permission',
		'Prise de parole': "Prends la parole sans en avoir eu l'autorisation",
		Dort: 'Dort sur sa table',
		'Refus de travail': 'Ne fait pas le travail demandé',
		Bavarde: "Bavarde ou s'amuse au lieu d'écouter ou de travailler",
		Triche: "Triche pendant l'évaluation",
		Absent: 'Absent',
		Projectile: 'Lance un objet à travers la classe',
		Exclusion: 'Exclus de cours',
	},
	ar: {
		Retard: 'تأخر عن حصة الرياضيات',
		Matériel: 'نقص المواد للدراسة',
		Devoirs: 'الواجبات المنزلية غير منجزة',
		Déplacement: 'التجول في الصف بدون إذن',
		'Prise de parole': 'تكلم بدون إذن',
		Dort: 'نوم على الطاولة',
		'Refus de travail': 'رفض العمل والقيام بالتمارين المطلوبة',
		Bavarde: 'الدردشة واللعب بدلاً من الاستماع إلى الدرس',
		Triche: 'الغش أثناء الامتحان',
		Absent: 'غياب',
		Projectile: 'رمى شيء عبر الغرفة',
		Exclusion: 'Exclus de cours',
	},
	en: {
		Retard: 'Arrives late to class',
		Matériel: 'Does not have his materials to work with',
		Devoirs: 'Homework not done',
		Déplacement: 'Unauthorized movement in the classroom.',
		'Prise de parole': 'Speaking without permission.',
		Dort: 'Sleeps in class',
		'Refus de travail': 'Refuses to do the requested work',
		Bavarde: 'Talks instead of listening or working.',
		Triche: 'Cheats during the assessment',
		Absent: 'Absent',
		Projectile: 'Throws an object across the classroom',
		Exclusion: 'Excluded from class',
	},
}
