export const warningCasesShort = [
	'Retard',
	'Matériel',
	'Devoirs',
	'Déplacement',
	'Prise de parole',
	'Dort',
	'Refus de travail',
	'Bavarde',
	'Triche',
	'Absent',
]

export const warningCases: Record<string, Record<string, string>> = {
	fr: {
		Retard: 'Arrive en retard en cours',
		Matériel: "N'a pas son matériel pour travailler",
		Devoirs: 'Devoirs non faits',
		Déplacement: 'Déplacement non autorisé',
		'Prise de parole': 'Prise de parole non autorisée',
		Dort: 'Dort en classe',
		'Refus de travail': 'Ne fait pas le travail demandé',
		Bavarde: "Bavarde au lieu d'écouter ou de travailler",
		Triche: "Triche pendant l'évaluation",
	},
	ar: {
		Retard: 'Arrive en retard en cours',
		Matériel: "N'a pas son matériel pour travailler",
		Devoirs: 'Devoirs non faits',
		Déplacement: 'Déplacement non autorisé',
		'Prise de parole': 'Prise de parole non autorisée',
		Dort: 'Dort en classe',
		'Refus de travail': 'Ne fait pas le travail demandé',
		Bavarde: "Bavarde au lieu d'écouter ou de travailler",
		Triche: "Triche pendant l'évaluation",
	},
	en: {
		Retard: 'Arrive en retard en cours',
		Matériel: "N'a pas son matériel pour travailler",
		Devoirs: 'Homework not done',
		Déplacement: 'Déplacement non autorisé',
		'Prise de parole': 'Prise de parole non autorisée',
		Dort: 'Dort en classe',
		'Refus de travail': 'Ne fait pas le travail demandé',
		Bavarde: "Bavarde au lieu d'écouter ou de travailler",
		Triche: "Triche pendant l'évaluation",
	},
}
